#!/bin/sh

VERSION="$0 V 0.1 (C) 2001 Artur Frysiak"
COMMAND=usage
VERBOSE=""
MODNAME=""
INIFILE=""

install ()
{
if [ -f ${INIFILE} ]; then
	echo "activating module '${MODNAME}.so' in ${INIFILE}" 1>&2
	perl -pi -e "s|^;extension=${MODNAME}.so|extension=${MODNAME}.so|g" ${INIFILE}
fi
if [ -f /var/lock/subsys/httpd ]; then
	/etc/rc.d/init.d/httpd restart 1>&2
fi
}

deinstall()
{
if [ -f ${INIFILE} ]; then
	echo "deactivating module '${MODNAME}.so' in ${INIFILE}" 1>&2
	perl -pi -e "s|^extension=${MODNAME}.so|;extension=${MODNAME}.so|g" $INIFILE
fi
if [ -f /var/lock/subsys/httpd ]; then
	/etc/rc.d/init.d/httpd restart 1>&2
fi
}

usage()
{
	echo $VERSION
	echo "Usage:"
	echo " $0 install MODNAME INIFILE"
	echo " $0 remove  MODNAME INIFILE"
}

if [ "$#" = 3 ]; then
	MODNAME="$2"
	INIFILE="$3"

	if [ "$1" = "install"]; then
		install
	else
		if [ "$1" = "remove"]; then
			remove
		else
			usage
		fi
	fi
else
	usage
	exit 1
fi

