#!/bin/sh

VERSION="$0 V 0.1 (C) 2001 Artur Frysiak"
COMMAND=usage
VERBOSE=""
MODNAME=""
INIFILE=""

install ()
{
if [ -f ${INIFILE} ] && ! grep -q "^extension[[:space:]]*=[[:space:]]*${MODNAME}.so" ${INIFILE} ; then
	echo "activating module '${MODNAME}.so' in ${INIFILE}" 1>&2
	echo "extension=${MODNAME}.so" >> ${INIFILE}
fi
if [ -f /var/lock/subsys/httpd ]; then
	/etc/rc.d/init.d/httpd restart 1>&2
fi
}

deinstall()
{
if [ -f ${INIFILE} ] && grep -q "^extension[[:space:]]*=[[:space:]]*${MODNAME}.so" ${INIFILE} ; then
	TMPFILE=`mktemp -q /tmp/php-module-install.XXXXXX`
	if [ $? -ne 0 ]; then
		echo "$0: Can't create temp file, exiting..."
		exit 1
	fi
	echo "deactivating module '${MODNAME}.so' in ${INIFILE}" 1>&2
	grep -v "^extension[[:space:]]*=[[:space:]]*${MODNAME}.so" > ${TMPFILE} < ${INIFILE}
	mv ${TMPFILE} ${INIFILE}
	chmod 644 ${INIFILE}
fi
if [ -f /var/lock/subsys/httpd ]; then
	/etc/rc.d/init.d/httpd restart 1>&2
fi
}

usage()
{
	echo $VERSION
	echo "Usage:"
	echo " $0 install MODNAME INIFILE"
	echo " $0 remove  MODNAME INIFILE"
}

if [ "$#" = 3 ]; then
	MODNAME="$2"
	INIFILE="$3"

	if [ "$1" = "install" ]; then
		install
	else
		if [ "$1" = "remove" ]; then
			deinstall
		else
			usage
		fi
	fi
else
	usage
	exit 1
fi

exit 0
